### ISSUE TITLE
Make call options

### ISSUE THREAD

**Issue by datso** [Carusto/react-native-pjsip#14]
Add ability to send custom headers and determine whether audio or video are enabled.

**Comment by james-ovens** [comment]
Documentation shows this as being possible:
`let options = {
  headers: {
    "P-Assserted-Identity": "Header example",
    "X-UA": "React native"
  }
}`

`let call = await endpoint.makeCall(account, destination, options);`

However it isn't there in the current version.

**Comment by datso** [comment]
Hello, please use with_video branch (https://github.com/Carusto/react-native-pjsip/tree/with-video), and iOS version. I will make a PR soon.

{
    "hdr_list": { "P-Assserted-Identity": "Header example", "X-UA": "React native" }
}

**Comment by james-ovens** [comment]
So the video branch on iOS will allow call options, but android doesn't?

**Comment by datso** [comment]
@james-ovens Yeap, I will make a PR on this weekend to support additional parameters for Java version.

**Comment by pohodnya** [comment]
@datso https://github.com/Carusto/react-native-pjsip/commit/23260490bbaa159e6719a99c848f5cfdfaf4e54c still work in progress?

How I can add custom header to call on ios?

```javascript
let options = { headers: { "P-Assserted-Identity": "Header example", "X-UA": "React native" } }
let call = await endpoint.makeCall(account, destination, options);
```
or
```javascript
let options = { hdr_list: { "P-Assserted-Identity": "Header example", "X-UA": "React native" } }
let call = await endpoint.makeCall(account, destination, options);
```

**Comment by datso** [comment]
Finally, I've decided to use camelCase, current master supports following configuration:
```
const callSettings = {
  audioCount: 1,
  videoCount: 1
}

const messageSettings = {
   headers: {
      "A": "B",
      "C": "D"
   },
   targetURI: "...",
   contentType: "...",
   body: "..."
}

endpoint.makeCall(account, destination, callSettings, messageSettings)
```
