### ISSUE TITLE
Most basic possible attempted use of react-native-pjsip not working as expected.

### ISSUE THREAD

**Issue by marcusegues** [Carusto/react-native-pjsip#20]
I started a completely new project, with the objective of making the simplest React/Redux app that is capable of registering and making calls using `react-native-pjsip`. [Here is the code](https://github.com/marcusegues/BasicExamplePjSip). 

The current issues are:
* On iOS and Android, it registers an account correctly, but when it tries to make a call, I get an inconsistent result on my SIP server, which displays "PJSIP syntax error exception when parsing 'Request Line' header" sometimes, and other times just works fine.
* Sometimes, when I click on 'Register', I don't get any reaction from my Emulator, and nothing on the server, and then eventually, the app stops working in the Emulator. I don't have any experience working with Android Studio, but it's weird that sometimes this app works perfectly fine and others it crashes.
Here are exactly all the steps I took in this project:

1) react-native init BasicExamplePjSip
2) npm install --save prop-types react-native-pjsip react-redux redux redux-thunk
3) Modify `/index.ios.js` and `/index.android.js` to both contain:
```
import { AppRegistry } from 'react-native';
import AppComponent from './src/index';

AppRegistry.registerComponent('RNPJSipBasicExample', () => AppComponent);
```

4) Follow installation instructions for react-native-pjsip on iOS: 
* Run `react-native link`
* Open the project in Xcode and in the `Build Settings` set `Enable Bitcode` to `No`
* Add code to `os/%PROJECT_NAME%/Info.plist`

5) Follow installation instructions for react-native-pjsip on Android:
* Add permissions & service to `android/app/src/main/AndroidManifest.xml`
* Run `react-native link`
* Add code to `android/app/src/main/java/com/xxx/MainActivity.java`

6) Start writing the React/Redux code, this is the order I took:
* `/src/index.js`:
* `configureStore.js`:
* `/actions/pjsip.js`, containing two synchronous action creators `createAccountSuccess` and `onAccountChanged` and three asynchronous action creators (thunks) `init`, `createAccount`, and `makeCall`
* Add reducers `/reducers/index.js` which uses `combineReducers` on just the reducer in `/reducers/pjsip`. State has just a `pjsip` key containing the object related to `react-native-pjsip`.
* Add `/constants/index.js` to export all the used constants.

8) Add some components to `/components`. This is simply `App` and `AppContainer` components, which show input fields to fill out for account registration. `AppContainer` connects `App` to the store so it can dispatch the actions in `/actions/pjsip.js`. `App also contains a component `MakeCallTest` which is just an input field with the extension to dial, and a button to make the call. Root component renders `AppContainer` inside of the react-redux `Provider`

9) `react-native run-ios` works, I have the app in the simulator. I try to register to my SIP server, it works, I try to make a call, and on the server I see: `PJSIP syntax error exception when parsing 'Request Line' header`. Sometimes this doesn't happen, sometimes it does. 

10) `react-native-run-android`

**Comment by datso** [comment]
It would be great to have `tcpdump` (or attach logs from server) and logs from `adb logcat`.
