### ISSUE TITLE
Echo and Noise Cancellation

### ISSUE THREAD

**Issue by dalwadi2** [Carusto/react-native-pjsip#24]
Hey, @datso .
have you done the echo cancellation and Noise Reduction in PJSIP configs.
I've read that we can do that but we've to set some Long value to it.
so if you have any idea about this.
please let me know.
thanks.

**Comment by datso** [comment]
Hi, I suppose EC and NR are configured by default in PJSIP. Are you interested in special configuration or have problems with EC/NR ?

**Comment by dalwadi2** [comment]
@datso I'm Intrested in Special Configuration.

**Comment by datso** [comment]
Adding those configurations should be pretty easy, PR is welcome.

**Comment by dalwadi2** [comment]
I thought you are going to help me with special configuration. @datso 
sorry to your welcome, but now I'm working on a product and have no time for new Experiments.
thanks @datso
