### ISSUE TITLE
Update pjsip

### ISSUE THREAD

**Issue by fcaride** [Carusto/react-native-pjsip#28]
Hi i tried to update pjsip using the script "vialerbuild" here: https://github.com/VoIPGRID/Vialer-pjsip-iOS

And im integrating the updated VialerPJSIP to this sdk but im getting some errors. Could you please update pjsip version? Im not familiar with that code .
Thanks!!!

**Comment by OpenKompani** [comment]
@datso  what version of PJSIP is the react-native-pjsip library currently running for Android and iOS

**Comment by datso** [comment]
Hi, what is the reason for update pjsip on IOS ?
As I remember Android uses 2.4.5, iOS 2.6, you can find the version in UA field of REGISTER message.

**Comment by OpenKompani** [comment]
I intend to compile android  to use 2.6. I intend using API Level 19 which means compiling for armeabi-v7a and x86 ABIs  only as they cover most devices and from what i have read armeabi-v7a  will still work on arm64-v8a ( though not the most performant) as well  I know the API level used does not work very well with x64 ABI architectures. Does Replacing the libpjsua2.so which was compiled using 2.4.5 with a .so file compiled with pjsip 2.6 introduce any breaking changes to the code

**Comment by datso** [comment]
Building C libs could be a tricky and very time expensive. Consider this repo as a starting point https://github.com/VoiSmart/pjsip-android-builder.

API's should be the same but you should update them by copying directory
_pjsip-2.6/pjsip-apps/src/pjsua/android/app/src/main/java/org_  
_react-native-pjsip/android/src/main/java/org_

and

_pjsip-2.6/pjsip-apps/src/pjsua/android/app/src/main/jniLibs_
_react-native-pjsip/android/src/main/jniLibs_
