### ISSUE TITLE
endpoint.createAccont is not a function

### ISSUE THREAD

**Issue by murugancmi** [Carusto/react-native-pjsip#31]
When  i try to register i am getting endpoint.createAccont is not a function bellow is my code sample 

	const endpoint = new Endpoint();
const state = await endpoint.start();
let account = await endpoint.createAccount(configuration);

**Comment by amen160** [comment]
the same with me
[TypeError: endpoint.createAccont is not a function. (In 'endpoint.createAccont()', 'endpoint.createAccont' is undefined)]
Can you help me?
@murugancmi
