### ISSUE TITLE
Not able to register - If change Port number 

### ISSUE THREAD

**Issue by murugancmi** [Carusto/react-native-pjsip#34]
When i try to register different port like 7060 getting register failure error

**Comment by datso** [comment]
Hello, please provide a SIP network trace (.pcap) or SIP logs from device.

**Comment by murugancmi** [comment]
i can't able to register , Means not able to connect sip server then how i can get trace may i send you my connect configuration

**Comment by murugancmi** [comment]
let configuration = {
                "name": 'AYOO',
                "username": agent,
                "domain": "139.59.92.65:7060",
                "password": password,
                "proxy": '139.59.92.65:7060;transport=udp',
                "transport": "TCP"
            };

self.chub.user = await endpoint.createAccount(configuration)

**Comment by murugancmi** [comment]
we are using opensip as a proxy server

**Comment by datso** [comment]
Hello, domain should not contain a port.
I will try to investigate the problem on this weekend.

**Comment by murugancmi** [comment]
Ok let me try without port in domain

**Comment by murugancmi** [comment]
This issue is fixed ?

**Comment by datso** [comment]
This is not an issue with the library. 
Your configuration is invalid, use proxy configuration for custom port and remove transport TCP because you already set it in proxy configuration.

If you found a bug in the library, please report an issue with logs attached.

**Comment by murugancmi** [comment]
Registration failed but i can able to make call ,Bellow is my configuration

let configuration = {
                "name": 'AYOO',
                "username": agent,
                "domain": "139.59.9.112",
                "password": password,
                "proxy":"sip:139.59.9.112:7060;transport=udp"
            };

**Comment by datso** [comment]
It would be better to ask an administrator of our SIP server where is the problem.
I think that it could be in Realm validation (e.g. domain).

**Comment by murugancmi** [comment]
Yes now i change domain name now it works
