### ISSUE TITLE
I dont't use redux,but it can't createAccont

### ISSUE THREAD

**Issue by ftb2010** [Carusto/react-native-pjsip#48]
let endpoint = new Endpoint();
let state = await endpoint.start();
let account = await endpoint.createAccont(configuration);
use this code can't createAccont; no result returned;
Could you please update your example using react-navigation and dva?

**Comment by datso** [comment]
There is no specific code that are related to redux in that library. Could you provide some logs what actually doesn't work?

**Comment by ftb2010** [comment]
@datso 
This is my dva demo,only use index.android.js to test createAccount,await can't be done.Could you please help me to solve it?
[react-native-dva-starter-master.zip](https://github.com/Carusto/react-native-pjsip/files/1585163/react-native-dva-starter-master.zip)

**Comment by datso** [comment]
Please provide the logs that shows the flow and issue. It would be also great if you don't use async for componentWillMount...

componentWillMount() {
  const endpoint = new Endpoint();
  endpoint.start().then((state) => {
    endpoint.createAccount(...configuration).then((account) => {
      console.log("Your account", account)
    })
  )
}
