### ISSUE TITLE
Headers does not works

### ISSUE THREAD

**Issue by pohodnya** [Carusto/react-native-pjsip#49]
I set the headers as shown [here](https://github.com/Carusto/react-native-pjsip/blob/master/docs/calls.md#initiate-a-call). But in the SIP trace there are no my headers.
```coffeescript
let options = {
    headers: {
        "P-Assserted-Identity": "Header example",
        "X-UA": "React native"
    }
};
let call = endpoint.makeCall(account, destination, options);
```
<img width="398" alt="printscreen" src="https://user-images.githubusercontent.com/10988731/34349851-2dc84fbe-ea46-11e7-8c9d-da310d1f667d.png">

**Comment by datso** [comment]
I didn't have a chance to update the docs for the latests version.
Currently library supports following configuration:
```
callSettings = {audioCount, videoCount, flag, requestKeyframeMethod}
msgData = {targetUri, headers, contentType, body}.
endpoint.makeCall(account, destination, callSettings, msgData)
```


So your code will be
```
const msgOptions = {
    headers: {
        "P-Assserted-Identity": "Header example",
        "X-UA": "React native"
    }
};
const call = endpoint.makeCall(account, destination, {audioCount: 1, videoCount: 0}, msgOptions);
```
